import { CaseStudy, PlaygroundItem } from './types';

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: 1,
    slug: "mta-open-source",
    title: "MTA Open Source Challenge",
    category: "Data Visualization Design",
    subhead: "Designing and coding a data visualization web app from the ground up",
    tags: ["UI/UX", "Mobile App"],
    imageUrl: "assets/imgs/Case1.png",
    description: "Designing and coding a data visualization web app from the ground up",
    timeline: "5 Weeks",
    role: "Designer, Developer",
    tools: "Figma, D3.js, CSS, HTML, AfterEffects"
  },
  {
    id: 2,
    slug: "mcdonalds-game",
    title: "McDonald’s Happy Meal Games",
    category: "Game and UI Design",
    subhead: "Designing for 4 unique mobile games",
    tags: ["Product Design", "Branding"],
    imageUrl: "assets/imgs/Mcdonalds/IHUsE9aVdEHPrcf2LaRZdN9th6c.png.webp",
    description: "Designing for 4 unique mobile games",
    timeline: "6 Months",
    role: "UI Designer",
    tools: "Figma, AfterEffects"
  },
  {
    id: 3,
    slug: "faceless-affair",
    title: "Faceless Affair",
    category: "Interactive Narrative",
    subhead: "An interactive mystery game",
    tags: ["UX Design", "Game Design"],
    imageUrl: "assets/imgs/Case6.png",
    description: "An interactive mystery game exploring narrative depth through digital interaction.",
    timeline: "8 Weeks",
    role: "UX Designer, Writer",
    tools: "Twine, Figma, Photoshop"
  },
  {
    id: 4,
    slug: "higher-ed-campaign",
    title: "Higher Education Campaign Design",
    category: "CAMPAIGN DESIGN",
    subhead: "Designing campaigns for universities",
    tags: ["Social Media", "Web Design"],
    imageUrl: "assets/imgs/Case3.png",
    description: "Designing campaigns for universities",
    timeline: "Ongoing",
    role: "Visual Designer",
    tools: "InDesign, AfterEffects, Figma",
    year: "2025-Ongoing"
  },
  {
    id: 5,
    slug: "editorial-design",
    title: "Editorial Design",
    category: "Typographic Motion",
    subhead: "Designing for Print",
    tags: ["Print Design", "Illustration"],
    imageUrl: "assets/imgs/Case5.png",
    description: "A typographic exploration of visual language in social movements.",
    timeline: "Ongoing",
    role: "Print Designer",
    tools: "Print Design, Branding"
  },
  {
    id: 6,
    slug: "secret-garden-viz",
    title: "The Secret Garden Data Visualization",
    category: "Information Design",
    subhead: "Exploring literature through data",
    tags: ["Information Design", "Web Design"],
    imageUrl: "assets/imgs/Case4.png",
    description: "Mapping the linguistic landscape of classic literature.",
    timeline: "5 Weeks",
    role: "Information Designer",
    tools: "D3.js, Python, Figma",
    externalUrl: "https://thesecretgardenindata.framer.website/"
  },
  {
    id: 7,
    slug: "kinetics-branding",
    title: "Kinetics: High-Performance Branding",
    category: "Brand Identity",
    tags: ["Visual Identity", "Typography"],
    imageUrl: "assets/imgs/Case4.png",
    description: "Dynamic brand system for an emerging electric bike manufacturer.",
    timeline: "12 Weeks",
    role: "Brand Strategist",
    tools: "Illustrator, AfterEffects"
  }
];

export const PLAYGROUND_ITEMS: PlaygroundItem[] = [
  { id: 1, title: "Illustration 1", type: "Illustration", imageUrl: "assets/imgs/Illustrations/AwyNGfGqy1hxj6dtt0TAXK0Yg.png.webp" },
  { id: 2, title: "Illustration 2", type: "Illustration", imageUrl: "assets/imgs/Illustrations/zNDsURFwBOOQueyIeJXQUSZrFs.png-2.webp" },
  { id: 3, title: "Illustration 3", type: "Illustration", imageUrl: "assets/imgs/Illustrations/L6fTSVsnrqGueVfMReeaL9jE3c.jpg.webp" },
  { id: 4, title: "Illustration 4", type: "Illustration", imageUrl: "assets/imgs/Illustrations/YTOJFYD3k1s1ooWETBpWRpIYN4.png.webp" },
  { id: 5, title: "Illustration 5", type: "Illustration", imageUrl: "assets/imgs/Illustrations/zUcKu6zqoIDE0fQrR1NuehvoX9U.png.webp" },
  { id: 6, title: "Illustration 6", type: "Illustration", imageUrl: "assets/imgs/Illustrations/ZAW7kxKKHmJ67TQ8lKehu0tY.jpg-2.webp" },
  { id: 7, title: "Illustration 7", type: "Illustration", imageUrl: "assets/imgs/Illustrations/cClUPjxZBsBGgWS9HmO9DbrQwtE.png.webp" },
  { id: 8, title: "Illustration 8", type: "Illustration", imageUrl: "assets/imgs/Illustrations/fPYWPSwlfeIqBEVfYuzpcHSmEc.png.webp" },
  { id: 9, title: "Illustration 9", type: "Illustration", imageUrl: "assets/imgs/Illustrations/zJgpXHLu6E7cVRADkIVcnfYCJ4.jpg-2.webp" },
  { id: 10, title: "Illustration 10", type: "Illustration", imageUrl: "assets/imgs/Illustrations/0qVV0p7z1Yl2UMzfegWjb37h8uM.jpg.webp" },
  { id: 11, title: "Illustration 11", type: "Illustration", imageUrl: "assets/imgs/Illustrations/n11RDBzGdR9TwfEpuu4l53ATnws.png.webp" },
  { id: 12, title: "Illustration 12", type: "Illustration", imageUrl: "assets/imgs/Illustrations/VGFYYoOd5ercBAP7zalwU1lln1c.png.webp" },
  { id: 13, title: "Illustration 13", type: "Illustration", imageUrl: "assets/imgs/Illustrations/q4ByAv0W2BoG67M0tW84HgW8.png.webp" },
  { id: 14, title: "Illustration 14", type: "Illustration", imageUrl: "assets/imgs/Illustrations/VYZKS1oXJzAvVBDyohO1iczXB8.png.webp" },
  { id: 15, title: "Illustration 15", type: "Illustration", imageUrl: "assets/imgs/Illustrations/5J7c9wpR2Uya2MYC7DgCZYmn1yM.png.webp" },
  { id: 16, title: "Illustration 16", type: "Illustration", imageUrl: "assets/imgs/Illustrations/n11RDBzGdR9TwfEpuu4l53ATnws.png-2.webp" },
  { id: 17, title: "Illustration 17", type: "Illustration", imageUrl: "assets/imgs/Illustrations/hBtiPv0430Zgy7vknMq7FqP9dD4-2.gif" },
  { id: 18, title: "Illustration 18", type: "Illustration", imageUrl: "assets/imgs/Illustrations/qazugpCOnVnqCBZkwNmCe0fGXE.jpg.webp" },
  { id: 19, title: "Illustration 19", type: "Illustration", imageUrl: "assets/imgs/Illustrations/sIljiZoLzkmQxt2gA2f4GcCauLU.png-2.webp" },
  { id: 20, title: "Illustration 20", type: "Illustration", imageUrl: "assets/imgs/Illustrations/dYT63JZpSJVDT8UgcZlt2YiS1zk-2.gif" },
  { id: 21, title: "Illustration 21", type: "Illustration", imageUrl: "assets/imgs/Illustrations/sK1Iyj11iXwDXm6Wpb42eICnU.png-2.webp" },
  { id: 22, title: "Illustration 22", type: "Illustration", imageUrl: "assets/imgs/Illustrations/7GunyZ9eH2ES50x9sfQ6E9VWgE.png.webp" },
  { id: 23, title: "Illustration 23", type: "Illustration", imageUrl: "assets/imgs/Illustrations/I6mEbK2ClTedyMOMlTw7GVT08I.png-2.webp" },
  { id: 24, title: "Illustration 24", type: "Illustration", imageUrl: "assets/imgs/Illustrations/RmKN5TvF7eYDZwYZShv8WC0LjM.png.webp" },
  { id: 25, title: "Illustration 25", type: "Illustration", imageUrl: "assets/imgs/Illustrations/jTNFhm6yAEEk2NZGgMSQhYEUI8.png.webp" },
  { id: 26, title: "Illustration 26", type: "Illustration", imageUrl: "assets/imgs/Illustrations/Artboard 1 copy-100.jpg" },
  { id: 27, title: "Illustration 27", type: "Illustration", imageUrl: "assets/imgs/Illustrations/VnPbBfvlDPvpxDD44duLMg8RgZg.png.webp" },
];